@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE3NTIwNjkzNTQsImV4cCI6MTc1MjA3NjU1NH0.Pk3BCmQPucFuWSYJSgp7BUkurUYp1jMZ9WkRGfiSUKw

### 🔐 Connexion et extraction du token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jules@example.com",
    "password": "motdepasse1"
}

### 🚀 Requête protégée avec le token
GET http://localhost:3000/auth/me
Authorization: Bearer {{token}}

### 🚪 Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

### 📝 Mise à jour du pseudo
PATCH http://localhost:3000/auth/me/pseudo
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "newPseudo": "Toto752"
}

### 📝 Mise à jour du mot de passe
PATCH http://localhost:3000/auth/me/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currentPassword": "motdepasse8",
    "newPassword": "motdepasse75"
}

### 🗑️ Suppression du compte
DELETE http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}