@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJpYXQiOjE3NTIwNjkzNTQsImV4cCI6MTc1MjA3NjU1NH0.Pk3BCmQPucFuWSYJSgp7BUkurUYp1jMZ9WkRGfiSUKw

### 🔐 Connexion et extraction du token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jules@example.com",
    "password": "motdepasse1"
}

## page me

### 📝 Mise à jour du mot de passe
PATCH http://localhost:3000/auth/me/password
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "currentPassword": "motdepasse8",
    "newPassword": "motdepasse75"
}

### 🗑️ Suppression du compte
DELETE http://localhost:3000/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}


## GAMES

### 🕹️ Liste des jeux
GET http://localhost:3000/games

### 🕹️ Détails d'un jeu spécifique
GET http://localhost:3000/games/1

## USERS
### All users
GET http://localhost:3000/users

## CHALLENGES
### All challenges
GET http://localhost:3000/challenges
### Specific challenge
GET http://localhost:3000/challenges/1
### Create challenge
POST http://localhost:3000/challenges
Content-Type: application/json

{
    "title": "Titre du challenge",
    "description": "Description du challenge",
    "rules": "Règles du challenge",
    "created_by": 1,
    "game_by": 1
}

### Likes of a specific challenge
GET http://localhost:3000/challenges/1/likes
### Add a like to a specific challenge
POST http://localhost:3000/challenges/1/likes
Content-Type: application/json

## PARTICIPATIONS
### All participations of a challenge
GET http://localhost:3000/challenges/1/participations
### Create participation
POST http://localhost:3000/participations
Content-Type: application/json

{
    "media_link": "Chemin vers le média",
    "description": "Description de la participation",
    "challenge_id": 1,
    "user_id": 1
}

