#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NTE5NzM4NDYsImV4cCI6MTc1MTk4MTA0Nn0.xexfNANRG23tcuNfCSUcyapV-zgn08NdVsvevcAx3uU

### 🔐 Connexion et extraction du token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jules@example.com",
    "password": "motdepasse1"
}

### 🚀 Requête protégée avec le token
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NTE5ODIyMDMsImV4cCI6MTc1MTk4OTQwM30.wjlFg7tyXRG9z_1UgWMw8vhWcpc32drNa249YX4bUB0

### 🚪 Logout
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NTE5ODIyMDMsImV4cCI6MTc1MTk4OTQwM30.wjlFg7tyXRG9z_1UgWMw8vhWcpc32drNa249YX4bUB0

